import Head from "next/head";
import Header from "../../components/header";
import Footer from "../../components/footer";
import useSWR from "swr";
import { fetchAPI, getMenuLinks } from "../../lib/api";

import styles from "../../styles/modules/Post.module.css";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Post({ slug, menuItems }) {
  const { data, error } = useSWR(`/api/posts/${slug}`, fetcher);
  if (error) return <div>Error...</div>;
  if (!data) return <div>Loading....</div>;

  return (
    <>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header menuItems={menuItems} />

      <main className={styles.post}>
        <h1>{data.title}</h1>
        {data.featuredImage?.node.mediaItemUrl ? (
          <img src={data.featuredImage?.node.mediaItemUrl} alt={data.title} />
        ) : null}
        <div dangerouslySetInnerHTML={{ __html: data.content }} />
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps({ params }) {
  const menuItems = await getMenuLinks("HEADER_MENU");

  return {
    props: {
      slug: params.slug,
      menuItems,
    },
  };
}

export async function getStaticPaths() {
  const allPosts = await fetchAPI(`
        query getAllPosts {
            posts {
                edges{
                    node {
                        slug
                    }
                }
            }
        }
    `);

  return {
    paths: allPosts.posts.edges.map(({ node }) => `/blog/${node.slug}`) || [],
    fallback: true,
  };
}
