import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import useSWR from "swr";
import { getMenuLinks } from "../lib/api";

import styles from "../styles/modules/Home.module.css";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home({ menuItems }) {
  const { data, error } = useSWR("/api/pages/homepage", fetcher);

  if (error) return <div>Error...</div>;
  if (!data) return <div>Loading....</div>;

  return (
    <>
      <Head>
        <title>Ivision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header menuItems={menuItems} />

      <main className={styles.main}>
        <div
          className={styles.wrapper}
          dangerouslySetInnerHTML={{ __html: data.content }}
        />
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps({ params }) {
  const menuItems = await getMenuLinks("HEADER_MENU");

  return {
    props: { menuItems },
  };
}
