import Head from "next/head";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Link from "next/link";
import { getAllVideos, getMenuLinks } from "../../lib/api";

import styles from "../../styles/modules/Videos.module.css";

export default function Videos({ allVideos: { nodes }, menuItems }) {
  const videos = nodes;
  if (!videos) return <div>Error....</div>;

  return (
    <>
      <Head>
        <title>Videos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header menuItems={menuItems} />

      <main>
        <h1>Videos</h1>
        <div className={styles.videos}>
          {videos.map((video) => (
            <Link href={`/videos/${video.slug}`} key={video.slug}>
              <a className={styles.video}>
                <img
                  src={
                    video.featuredImage?.node.mediaItemUrl
                      ? video.featuredImage?.node.mediaItemUrl
                      : "./placeholder.png"
                  }
                />
                <h2>{video.title}</h2>
                <div dangerouslySetInnerHTML={{ __html: video.excerpt }} />
              </a>
            </Link>
          ))}
        </div>
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const allVideos = await getAllVideos();
  const menuItems = await getMenuLinks("HEADER_MENU");

  return {
    props: { allVideos, menuItems },
  };
}
